/// Flutter icons FinalCustomIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FinalCustomIcons
///      fonts:
///       - asset: fonts/FinalCustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FinalCustomIcons {
  FinalCustomIcons._();

  static const _kFontFam = 'FinalCustomIcons';
  static const String? _kFontPkg = null;

  static const IconData back = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData timer = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData save = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
